[package]
name = "quiet_custodian"
version = "0.1.0"
authors = ["richardleesimpson <github.elag9@passmail.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "6.1.1"
